language: java

jdk:
  - oraclejdk8
  - openjdk8
  - openjdk9

sudo: required

services:
  - docker
  
before_script:
  - docker pull babim/squid:auth
#before_install:
#  - docker run -e USERNAME=foo -e PASSWORD=bar -p 3128:3128 babim/squid:auth
  
install: gradle build -x test
script: 
  - docker run -d -e USERNAME=foo -e PASSWORD=bar -p 3128:3128 babim/squid:auth
  - gradle test jacocoTestReport

after_success:
  - gradle jacocoTestReport coveralls
